[tool.autopep8]
max_line_length = 120

[tool.isort]
multi_line_output = 5
line_length       = 119

[tool.pytest.ini_options]
testpaths = ["tests"] # Search for tests in tests/
addopts = "--cov . --cov plugins --cov-report=term-missing --no-cov-on-fail"
# --cov-fail-under 80"

[tool.coverage.run]
omit = [ "tests/*", "venv/*", "dist.win32/*" ]
plugins = [ "coverage_conditional_plugin" ]

[tool.coverage.coverage_conditional_plugin.rules]
# Yes, the sense of all of these is inverted, because else it ends up
# inverted at *every* use.
sys-platform-win32 = "sys_platform != 'win32'"
sys-platform-not-win32 = "sys_platform == 'win32'"
sys-platform-darwin = "sys_platform != 'darwin'"
sys-platform-not-darwin = "sys_platform == 'darwin'"
sys-platform-linux = "sys_platform != 'linux'"
sys-platform-not-linux = "sys_platform == 'linux'"
sys-platform-not-known = "sys_platform in ('darwin', 'linux', 'win32')"

[tool.pyright]
# pythonPlatform = 'Darwin'
