# This workflow will:
#
#   * install Python dependencies
#   * lint with a single version of Python
#
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Push-Checks

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v2.3.1
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel flake8 pytest
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    
    - name: Setup flake8 annotations
      uses: rbialon/flake8-annotations@v1
    
    - name: Lint with flake8
      env:
        ROOT_SHA: ${{github.base_ref}}
      run: |
        DATA=$(jq --raw-output .before $GITHUB_EVENT_PATH)

        echo "DATA: ${DATA}"
        # stop the build if there are Python syntax errors or undefined names, ignore existing 
        git diff "$DATA" | flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --diff
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        git diff "$DATA" | flake8 . --count --statistics --diff
